In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import pandas as pd
import numpy as np
from sklearn import preprocessing,cross_decomposition,model_selection,metrics
import matplotlib.pyplot as plt
import seaborn as sns
import xgboost as xgb
%matplotlib inline
import dateutil
from tqdm import tqdm
from sklearn import linear_model
import datetime
import numpy as np
import pandas as pd

import plotly.graph_objects as go
from ipywidgets import widgets
import statsmodels.api as sm
import statsmodels.formula.api as smf
from statsmodels import tsa
import numpy as np
import pandas as pd

import plotly.graph_objects as go
from ipywidgets import widgets

In [3]:
confirmedGlobal=pd.read_csv('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv',encoding='utf-8',na_values=None)
confirmedGlobal

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,8/15/20,8/16/20,8/17/20,8/18/20,8/19/20,8/20/20,8/21/20,8/22/20,8/23/20,8/24/20
0,NaN,Afghanistan,33.939110,67.709953,0,0,0,0,0,0,...,37551,37596,37599,37599,37599,37856,37894,37953,37999,38054
1,NaN,Albania,41.153300,20.168300,0,0,0,0,0,0,...,7260,7380,7499,7654,7812,7967,8119,8275,8427,8605
2,NaN,Algeria,28.033900,1.659600,0,0,0,0,0,0,...,38133,38583,39025,39444,39847,40258,40667,41068,41460,41858
3,NaN,Andorra,42.506300,1.521800,0,0,0,0,0,0,...,989,989,1005,1005,1024,1024,1045,1045,1045,1060
4,NaN,Angola,-11.202700,17.873900,0,0,0,0,0,0,...,1879,1906,1935,1966,2015,2044,2068,2134,2171,2222
5,NaN,Antigua and Barbuda,17.060800,-61.796400,0,0,0,0,0,0,...,93,93,93,93,94,94,94,94,94,94
6,NaN,Argentina,-38.416100,-63.616700,0,0,0,0,0,0,...,289100,294569,299126,305966,312659,320884,329043,336802,342154,350867
7,NaN,Armenia,40.069100,45.038200,0,0,0,0,0,0,...,41495,41663,41701,41846,42056,42319,42477,42616,42792,42825
8,Australian Capital Territory,Australia,-35.473500,149.012400,0,0,0,0,0,0,...,113,113,113,113,113,113,113,113,113,113
9,New South Wales,Australia,-33.868800,151.209300,0,0,0,0,3,4,...,3950,3957,3959,3966,3971,3972,3981,3985,3988,3991
10,Northern Territory,Australia,-12.463400,130.845600,0,0,0,0,0,0,...,33,33,33,33,33,33,33,33,33,33
11,Queensland,Australia,-27.469800,153.025100,0,0,0,0,0,0,...,1091,1091,1091,1092,1093,1094,1103,1105,1106,1106
12,South Australia,Australia,-34.928500,138.600700,0,0,0,0,0,0,...,460,461,462,462,462,462,462,462,463,463
13,Tasmania,Australia,-42.882100,147.327200,0,0,0,0,0,0,...,230,230,230,230,230,230,230,230,230,230
14,Victoria,Australia,-37.813600,144.963100,0,0,0,0,1,1,...,16764,17027,17238,17446,17683,17852,18029,18231,18330,18464
15,Western Australia,Australia,-31.950500,115.860500,0,0,0,0,0,0,...,646,646,647,647,651,651,651,652,652,653
16,NaN,Austria,47.516200,14.550100,0,0,0,0,0,0,...,23179,23370,23534,23829,24084,24431,24762,25062,25253,25495
17,NaN,Azerbaijan,40.143100,47.576900,0,0,0,0,0,0,...,34107,34219,34343,34474,34620,34759,34921,35105,35274,35426
18,NaN,Bahamas,25.025885,-78.035889,0,0,0,0,0,0,...,1252,1315,1329,1424,1531,1610,1703,1703,1765,1765
19,NaN,Bahrain,26.027500,50.550000,0,0,0,0,0,0,...,46430,46835,47185,47581,47950,48303,48661,49038,49330,49719
20,NaN,Bangladesh,23.685000,90.356300,0,0,0,0,0,0,...,274525,276549,279144,282344,285091,287959,290360,292625,294598,297083
21,NaN,Barbados,13.193900,-59.543200,0,0,0,0,0,0,...,150,151,152,153,155,156,157,158,161,161
22,NaN,Belarus,53.709800,27.953400,0,0,0,0,0,0,...,69308,69516,69589,69673,69801,69950,70111,70285,70468,70645
23,NaN,Belgium,50.833300,4.469936,0,0,0,0,0,0,...,77869,78323,78534,78897,79479,80178,80894,81468,81936,82092
24,NaN,Belize,17.189900,-88.497600,0,0,0,0,0,0,...,388,452,475,475,553,605,648,668,686,713
25,NaN,Benin,9.307700,2.315800,0,0,0,0,0,0,...,2063,2063,2063,2063,2095,2095,2095,2115,2115,2115
26,NaN,Bhutan,27.514200,90.433600,0,0,0,0,0,0,...,133,138,141,147,147,153,154,155,155,156
27,NaN,Bolivia,-16.290200,-63.588700,0,0,0,0,0,0,...,99146,100344,101223,103019,105050,106065,107435,108427,109149,110148
28,NaN,Bosnia and Herzegovina,43.915900,17.679100,0,0,0,0,0,0,...,15801,15801,16111,16351,16691,17029,17396,17715,17715,18029
29,NaN,Botswana,-22.328500,24.684900,0,0,0,0,0,0,...,1214,1214,1308,1308,1308,1308,1308,1308,1308,1562
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
236,NaN,Thailand,15.870032,100.992541,2,3,5,7,8,8,...,3376,3378,3378,3382,3382,3389,3390,3390,3395,3402
237,NaN,Timor-Leste,-8.874217,125.727539,0,0,0,0,0,0,...,25,25,25,25,25,25,25,26,26,26
238,NaN,Togo,8.619500,0.824800,0,0,0,0,0,0,...,1130,1147,1154,1173,1190,1212,1239,1275,1277,1295
239,NaN,Trinidad and Tobago,10.691800,-61.222500,0,0,0,0,0,0,...,497,552,588,629,686,767,864,930,1007,1099
240,NaN,Tunisia,33.886917,9.537499,0,0,0,0,0,0,...,2023,2107,2185,2314,2427,2543,2607,2738,2818,2893
241,NaN,Turkey,38.963700,35.243300,0,0,0,0,0,0,...,248117,249309,250542,251805,253108,254520,255723,257032,258249,259692
242,NaN,US,40.000000,-100.000000,1,1,2,2,5,5,...,5361165,5403213,5438325,5482416,5529824,5573847,5622540,5667112,5701679,5739724
243,NaN,Uganda,1.373333,32.290275,0,0,0,0,0,0,...,1434,1500,1560,1603,1656,1750,1848,2166,2263,2362
244,NaN,Ukraine,48.379400,31.165600,0,0,0,0,0,0,...,91795,93490,95007,96653,98658,100810,102948,105337,107379,109234
245,NaN,United Arab Emirates,23.424076,53.847818,0,0,0,0,0,0,...,64102,64312,64541,64906,65341,65802,66193,66617,67007,67282
246,Anguilla,United Kingdom,18.220600,-63.068600,0,0,0,0,0,0,...,3,3,3,3,3,3,3,3,3,3
247,Bermuda,United Kingdom,32.307800,-64.750500,0,0,0,0,0,0,...,162,162,166,166,166,166,167,167,167,168
248,British Virgin Islands,United Kingdom,18.420700,-64.640000,0,0,0,0,0,0,...,9,9,9,11,11,11,21,21,21,21
249,Cayman Islands,United Kingdom,19.313300,-81.254600,0,0,0,0,0,0,...,203,203,203,203,205,205,205,205,205,205
250,Channel Islands,United Kingdom,49.372300,-2.364400,0,0,0,0,0,0,...,607,607,609,609,613,613,614,614,614,616
251,Falkland Islands (Malvinas),United Kingdom,-51.796300,-59.523600,0,0,0,0,0,0,...,13,13,13,13,13,13,13,13,13,13
252,Gibraltar,United Kingdom,36.140800,-5.353600,0,0,0,0,0,0,...,209,215,217,222,223,229,231,239,246,248
253,Isle of Man,United Kingdom,54.236100,-4.548100,0,0,0,0,0,0,...,336,336,336,336,336,336,336,336,336,336
254,Montserrat,United Kingdom,16.742498,-62.187366,0,0,0,0,0,0,...,13,13,13,13,13,13,13,13,13,13
255,Turks and Caicos Islands,United Kingdom,21.694000,-71.797900,0,0,0,0,0,0,...,298,298,298,315,327,334,347,383,383,383
256,NaN,United Kingdom,55.378100,-3.436000,0,0,0,0,0,0,...,317379,318484,319197,320286,321098,322280,323313,324601,325642,326614
257,NaN,Uruguay,-32.522800,-55.765800,0,0,0,0,0,0,...,1434,1440,1457,1485,1493,1506,1516,1521,1527,1533
258,NaN,Uzbekistan,41.377491,64.585262,0,0,0,0,0,0,...,34528,35329,35702,36352,37112,37547,38074,38532,38946,39348
259,NaN,Venezuela,6.423800,-66.589700,0,0,0,0,0,0,...,32607,33755,34802,35697,36868,37567,38219,38957,39564,40338
260,NaN,Vietnam,14.058324,108.277199,0,2,2,2,2,2,...,951,964,983,989,994,1007,1009,1014,1016,1022
261,NaN,West Bank and Gaza,31.952200,35.233200,0,0,0,0,0,0,...,16153,16534,16844,17306,17606,17989,18313,18476,18802,19213
262,NaN,Western Sahara,24.215500,-12.885800,0,0,0,0,0,0,...,10,10,10,10,10,10,10,10,10,10
263,NaN,Yemen,15.552727,48.516388,0,0,0,0,0,0,...,1858,1869,1882,1889,1892,1899,1906,1907,1911,1916
264,NaN,Zambia,-13.133897,27.849332,0,0,0,0,0,0,...,9186,9343,9839,9981,10218,10372,10627,10831,11082,11148
265,NaN,Zimbabwe,-19.015438,29.154857,0,0,0,0,0,0,...,5176,5261,5308,5378,5643,5745,5815,5893,5930,6070

In [4]:
deathGLobal=pd.read_csv('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv')
deathGLobal

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,8/15/20,8/16/20,8/17/20,8/18/20,8/19/20,8/20/20,8/21/20,8/22/20,8/23/20,8/24/20
0,NaN,Afghanistan,33.939110,67.709953,0,0,0,0,0,0,...,1370,1375,1375,1375,1375,1385,1385,1385,1387,1389
1,NaN,Albania,41.153300,20.168300,0,0,0,0,0,0,...,225,228,230,232,234,238,240,245,250,254
2,NaN,Algeria,28.033900,1.659600,0,0,0,0,0,0,...,1360,1370,1379,1391,1402,1411,1418,1424,1435,1446
3,NaN,Andorra,42.506300,1.521800,0,0,0,0,0,0,...,53,53,53,53,53,53,53,53,53,53
4,NaN,Angola,-11.202700,17.873900,0,0,0,0,0,0,...,86,88,88,90,92,93,94,94,96,100
5,NaN,Antigua and Barbuda,17.060800,-61.796400,0,0,0,0,0,0,...,3,3,3,3,3,3,3,3,3,3
6,NaN,Argentina,-38.416100,-63.616700,0,0,0,0,0,0,...,5637,5703,5814,6048,6330,6517,6730,6848,6985,7366
7,NaN,Armenia,40.069100,45.038200,0,0,0,0,0,0,...,817,818,824,832,833,836,842,850,852,854
8,Australian Capital Territory,Australia,-35.473500,149.012400,0,0,0,0,0,0,...,3,3,3,3,3,3,3,3,3,3
9,New South Wales,Australia,-33.868800,151.209300,0,0,0,0,0,0,...,52,52,52,52,52,52,52,52,52,52
10,Northern Territory,Australia,-12.463400,130.845600,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,Queensland,Australia,-27.469800,153.025100,0,0,0,0,0,0,...,6,6,6,6,6,6,6,6,6,6
12,South Australia,Australia,-34.928500,138.600700,0,0,0,0,0,0,...,4,4,4,4,4,4,4,4,4,4
13,Tasmania,Australia,-42.882100,147.327200,0,0,0,0,0,0,...,13,13,13,13,13,13,13,13,13,13
14,Victoria,Australia,-37.813600,144.963100,0,0,0,0,0,0,...,309,334,351,363,376,385,398,415,430,438
15,Western Australia,Australia,-31.950500,115.860500,0,0,0,0,0,0,...,9,9,9,9,9,9,9,9,9,9
16,NaN,Austria,47.516200,14.550100,0,0,0,0,0,0,...,728,728,729,729,729,729,730,732,732,733
17,NaN,Azerbaijan,40.143100,47.576900,0,0,0,0,0,0,...,506,506,508,509,510,510,512,515,518,519
18,NaN,Bahamas,25.025885,-78.035889,0,0,0,0,0,0,...,17,18,19,20,22,23,27,27,29,29
19,NaN,Bahrain,26.027500,50.550000,0,0,0,0,0,0,...,170,170,173,175,178,179,181,183,184,185
20,NaN,Bangladesh,23.685000,90.356300,0,0,0,0,0,0,...,3625,3657,3694,3740,3781,3822,3861,3907,3941,3983
21,NaN,Barbados,13.193900,-59.543200,0,0,0,0,0,0,...,7,7,7,7,7,7,7,7,7,7
22,NaN,Belarus,53.709800,27.953400,0,0,0,0,0,0,...,603,610,613,617,622,627,632,637,642,646
23,NaN,Belgium,50.833300,4.469936,0,0,0,0,0,0,...,9935,9939,9944,9959,9969,9976,9985,9988,9992,9996
24,NaN,Belize,17.189900,-88.497600,0,0,0,0,0,0,...,3,3,4,4,4,5,5,6,6,10
25,NaN,Benin,9.307700,2.315800,0,0,0,0,0,0,...,39,39,39,39,39,39,39,39,39,39
26,NaN,Bhutan,27.514200,90.433600,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27,NaN,Bolivia,-16.290200,-63.588700,0,0,0,0,0,0,...,4003,4058,4123,4172,4233,4305,4366,4442,4509,4578
28,NaN,Bosnia and Herzegovina,43.915900,17.679100,0,0,0,0,0,0,...,471,471,486,495,507,515,526,532,532,547
29,NaN,Botswana,-22.328500,24.684900,0,0,0,0,0,0,...,3,3,3,3,3,3,3,3,3,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
236,NaN,Thailand,15.870032,100.992541,0,0,0,0,0,0,...,58,58,58,58,58,58,58,58,58,58
237,NaN,Timor-Leste,-8.874217,125.727539,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
238,NaN,Togo,8.619500,0.824800,0,0,0,0,0,0,...,27,27,27,27,27,27,27,27,27,27
239,NaN,Trinidad and Tobago,10.691800,-61.222500,0,0,0,0,0,0,...,10,11,12,12,12,12,12,13,14,15
240,NaN,Tunisia,33.886917,9.537499,0,0,0,0,0,0,...,54,54,56,57,60,63,64,68,71,71
241,NaN,Turkey,38.963700,35.243300,0,0,0,0,0,0,...,5955,5974,5996,6016,6039,6058,6080,6102,6121,6139
242,NaN,US,40.000000,-100.000000,0,0,0,0,0,0,...,169481,170052,170497,171821,173177,174255,175370,176353,176802,177252
243,NaN,Uganda,1.373333,32.290275,0,0,0,0,0,0,...,13,13,15,15,16,19,19,20,20,22
244,NaN,Ukraine,48.379400,31.165600,0,0,0,0,0,0,...,2076,2100,2122,2152,2182,2225,2248,2286,2313,2335
245,NaN,United Arab Emirates,23.424076,53.847818,0,0,0,0,0,0,...,361,364,364,366,367,369,370,372,375,376
246,Anguilla,United Kingdom,18.220600,-63.068600,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
247,Bermuda,United Kingdom,32.307800,-64.750500,0,0,0,0,0,0,...,9,9,9,9,9,9,9,9,9,9
248,British Virgin Islands,United Kingdom,18.420700,-64.640000,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
249,Cayman Islands,United Kingdom,19.313300,-81.254600,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
250,Channel Islands,United Kingdom,49.372300,-2.364400,0,0,0,0,0,0,...,47,47,47,47,48,48,48,48,48,48
251,Falkland Islands (Malvinas),United Kingdom,-51.796300,-59.523600,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
252,Gibraltar,United Kingdom,36.140800,-5.353600,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
253,Isle of Man,United Kingdom,54.236100,-4.548100,0,0,0,0,0,0,...,24,24,24,24,24,24,24,24,24,24
254,Montserrat,United Kingdom,16.742498,-62.187366,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
255,Turks and Caicos Islands,United Kingdom,21.694000,-71.797900,0,0,0,0,0,0,...,2,2,2,2,2,2,2,2,2,2
256,NaN,United Kingdom,55.378100,-3.436000,0,0,0,0,0,0,...,41361,41366,41369,41381,41397,41403,41405,41423,41429,41433
257,NaN,Uruguay,-32.522800,-55.765800,0,0,0,0,0,0,...,38,38,40,40,40,41,42,42,42,42
258,NaN,Uzbekistan,41.377491,64.585262,0,0,0,0,0,0,...,225,232,236,242,248,252,260,267,273,280
259,NaN,Venezuela,6.423800,-66.589700,0,0,0,0,0,0,...,276,281,288,297,303,311,317,323,329,337
260,NaN,Vietnam,14.058324,108.277199,0,0,0,0,0,0,...,24,24,25,26,25,25,25,26,27,27
261,NaN,West Bank and Gaza,31.952200,35.233200,0,0,0,0,0,0,...,108,110,113,113,119,120,122,125,128,133
262,NaN,Western Sahara,24.215500,-12.885800,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
263,NaN,Yemen,15.552727,48.516388,0,0,0,0,0,0,...,528,530,535,537,539,541,542,546,553,555
264,NaN,Zambia,-13.133897,27.849332,0,0,0,0,0,0,...,260,260,264,264,269,274,277,279,280,280
265,NaN,Zimbabwe,-19.015438,29.154857,0,0,0,0,0,0,...,130,132,135,141,150,151,152,153,155,155

In [5]:
recoverGlobal=pd.read_csv('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv')
recoverGlobal

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,8/15/20,8/16/20,8/17/20,8/18/20,8/19/20,8/20/20,8/21/20,8/22/20,8/23/20,8/24/20
0,NaN,Afghanistan,33.939110,67.709953,0,0,0,0,0,0,...,27166,27166,27166,27166,27166,27681,28016,28016,28180,28360
1,NaN,Albania,41.153300,20.168300,0,0,0,0,0,0,...,3746,3794,3816,3871,3928,3986,4096,4184,4332,4413
2,NaN,Algeria,28.033900,1.659600,0,0,0,0,0,0,...,26644,27017,27347,27653,27971,28281,28587,28874,29142,29369
3,NaN,Andorra,42.506300,1.521800,0,0,0,0,0,0,...,863,863,869,869,875,875,875,875,875,877
4,NaN,Angola,-11.202700,17.873900,0,0,0,0,0,0,...,628,628,632,667,698,742,804,814,818,877
5,NaN,Antigua and Barbuda,17.060800,-61.796400,0,0,0,0,0,0,...,83,88,88,88,88,89,89,89,89,89
6,NaN,Argentina,-38.416100,-63.616700,0,0,0,0,0,0,...,205697,211702,217850,223531,228725,233651,239806,245781,251400,256789
7,NaN,Armenia,40.069100,45.038200,0,0,0,0,0,0,...,34484,34584,34655,34982,35226,35476,35693,35907,35991,36049
8,Australian Capital Territory,Australia,-35.473500,149.012400,0,0,0,0,0,0,...,110,110,110,110,110,110,110,110,110,110
9,New South Wales,Australia,-33.868800,151.209300,0,0,0,0,0,0,...,2994,2994,2994,2994,2995,2994,2994,2994,2994,2994
10,Northern Territory,Australia,-12.463400,130.845600,0,0,0,0,0,0,...,31,31,31,31,31,31,31,31,31,31
11,Queensland,Australia,-27.469800,153.025100,0,0,0,0,0,0,...,1079,1079,1079,1079,1081,1082,1082,1082,1082,1082
12,South Australia,Australia,-34.928500,138.600700,0,0,0,0,0,0,...,449,450,450,451,452,452,452,452,456,456
13,Tasmania,Australia,-42.882100,147.327200,0,0,0,0,0,0,...,216,216,216,216,216,216,216,216,216,216
14,Victoria,Australia,-37.813600,144.963100,0,0,0,0,0,0,...,8121,8570,9023,9413,9729,12334,12940,13239,13708,14077
15,Western Australia,Australia,-31.950500,115.860500,0,0,0,0,0,0,...,633,633,633,633,633,633,633,634,634,635
16,NaN,Austria,47.516200,14.550100,0,0,0,0,0,0,...,20627,20681,20765,20870,20958,21093,21260,21406,21558,21657
17,NaN,Azerbaijan,40.143100,47.576900,0,0,0,0,0,0,...,31697,31875,32042,32201,32363,32511,32682,32842,32993,33104
18,NaN,Bahamas,25.025885,-78.035889,0,0,0,0,0,0,...,160,189,191,203,209,211,221,221,227,227
19,NaN,Bahrain,26.027500,50.550000,0,0,0,0,0,0,...,42806,43128,43529,43921,44278,44628,45166,45589,45981,46311
20,NaN,Bangladesh,23.685000,90.356300,0,0,0,0,0,0,...,157635,158950,160591,162825,165738,168991,172615,175567,179091,182875
21,NaN,Barbados,13.193900,-59.543200,0,0,0,0,0,0,...,121,122,122,122,123,123,124,126,132,132
22,NaN,Belarus,53.709800,27.953400,0,0,0,0,0,0,...,66452,67072,67149,67339,67647,67929,68256,68577,68839,68925
23,NaN,Belgium,50.833300,4.469936,0,0,0,0,0,0,...,17981,17994,18003,18048,18078,18131,18165,18204,18225,18242
24,NaN,Belize,17.189900,-88.497600,0,0,0,0,0,0,...,35,35,38,38,38,38,43,44,44,45
25,NaN,Benin,9.307700,2.315800,0,0,0,0,0,0,...,1690,1690,1690,1690,1690,1705,1705,1705,1705,1705
26,NaN,Bhutan,27.514200,90.433600,0,0,0,0,0,0,...,102,102,103,103,103,108,110,112,112,117
27,NaN,Bolivia,-16.290200,-63.588700,0,0,0,0,0,0,...,35638,36491,37471,38623,39965,41111,42141,43887,45396,47050
28,NaN,Bosnia and Herzegovina,43.915900,17.679100,0,0,0,0,0,0,...,9619,9619,9856,10279,10711,10881,11157,11329,11329,11861
29,NaN,Botswana,-22.328500,24.684900,0,0,0,0,0,0,...,120,120,136,136,136,136,136,136,136,199
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
223,NaN,Thailand,15.870032,100.992541,0,0,0,0,2,2,...,3193,3194,3194,3199,3199,3218,3219,3220,3221,3229
224,NaN,Timor-Leste,-8.874200,125.727500,0,0,0,0,0,0,...,24,24,24,24,25,25,25,25,25,25
225,NaN,Togo,8.619500,0.824800,0,0,0,0,0,0,...,836,843,858,868,875,878,891,903,910,914
226,NaN,Trinidad and Tobago,10.691800,-61.222500,0,0,0,0,0,0,...,139,140,140,140,140,140,162,165,165,165
227,NaN,Tunisia,33.886917,9.537499,0,0,0,0,0,0,...,1327,1358,1362,1370,1395,1397,1420,1434,1443,1454
228,NaN,Turkey,38.963700,35.243300,0,0,0,0,0,0,...,229972,230969,231971,232913,233915,234797,235569,236370,237165,237908
229,NaN,US,40.000000,-100.000000,0,0,0,0,0,0,...,1818527,1833067,1865580,1898159,1925049,1947035,1965056,1985484,1997761,2020774
230,NaN,Uganda,1.373333,32.290275,0,0,0,0,0,0,...,1142,1142,1165,1165,1188,1194,1199,1199,1199,1248
231,NaN,Ukraine,48.379400,31.165600,0,0,0,0,0,0,...,48946,49346,49692,50508,51358,52086,52769,53458,53968,54262
232,NaN,United Arab Emirates,23.424076,53.847818,0,0,0,0,0,0,...,57571,57694,57794,57909,58022,58153,58296,58408,58488,58582
233,Anguilla,United Kingdom,18.220600,-63.068600,0,0,0,0,0,0,...,3,3,3,3,3,3,3,3,3,3
234,Bermuda,United Kingdom,32.307800,-64.750500,0,0,0,0,0,0,...,147,147,147,147,147,147,147,149,149,150
235,British Virgin Islands,United Kingdom,18.420700,-64.640000,0,0,0,0,0,0,...,7,7,7,8,8,8,8,8,8,8
236,Cayman Islands,United Kingdom,19.313300,-81.254600,0,0,0,0,0,0,...,202,202,202,202,202,202,202,202,202,202
237,Channel Islands,United Kingdom,49.372300,-2.364400,0,0,0,0,0,0,...,545,545,545,545,545,545,545,545,545,545
238,Falkland Islands (Malvinas),United Kingdom,-51.796300,-59.523600,0,0,0,0,0,0,...,13,13,13,13,13,13,13,13,13,13
239,Gibraltar,United Kingdom,36.140800,-5.353600,0,0,0,0,0,0,...,190,190,194,195,197,200,200,201,201,203
240,Isle of Man,United Kingdom,54.236100,-4.548100,0,0,0,0,0,0,...,312,312,312,312,312,312,312,312,312,312
241,Montserrat,United Kingdom,16.742498,-62.187366,0,0,0,0,0,0,...,12,12,12,12,12,12,12,12,12,12
242,Turks and Caicos Islands,United Kingdom,21.694000,-71.797900,0,0,0,0,0,0,...,55,55,55,56,56,102,102,102,102,102
243,NaN,United Kingdom,55.378100,-3.436000,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
244,NaN,Uruguay,-32.522800,-55.765800,0,0,0,0,0,0,...,1194,1200,1205,1219,1228,1242,1249,1264,1276,1295
245,NaN,Uzbekistan,41.377491,64.585262,0,0,0,0,0,0,...,29328,30973,30973,32062,32944,33261,33989,34576,34987,35551
246,NaN,Venezuela,6.423800,-66.589700,0,0,0,0,0,0,...,21747,22700,23575,24561,25416,26330,27306,28453,29966,31080
247,NaN,Vietnam,14.058324,108.277199,0,0,0,0,0,0,...,447,456,467,526,533,542,545,563,568,587
248,NaN,West Bank and Gaza,31.952200,35.233200,0,0,0,0,0,0,...,9388,9838,9906,9939,10312,10682,11102,11103,11843,11870
249,NaN,Western Sahara,24.215500,-12.885800,0,0,0,0,0,0,...,8,8,8,8,8,8,8,8,8,8
250,NaN,Yemen,15.552727,48.516388,0,0,0,0,0,0,...,1013,1013,1045,1052,1055,1058,1058,1066,1086,1090
251,NaN,Zambia,-13.133897,27.849332,0,0,0,0,0,0,...,8065,8412,8575,8776,9126,9126,9126,9942,9942,10208
252,NaN,Zimbabwe,-19.015438,29.154857,0,0,0,0,0,0,...,2047,2092,3848,4105,4442,4525,4587,4629,4872,4950

In [14]:
confirmedGlobal['NewContryCode']=confirmedGlobal['Country/Region']+confirmedGlobal['Province/State'].fillna('')
deathGLobal['NewContryCode']=deathGLobal['Country/Region']+deathGLobal['Province/State'].fillna('')
recoverGlobal['NewContryCode']=recoverGlobal['Country/Region']+recoverGlobal['Province/State'].fillna(' ')
recoverGlobal

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,8/16/20,8/17/20,8/18/20,8/19/20,8/20/20,8/21/20,8/22/20,8/23/20,8/24/20,NewContryCode
0,NaN,Afghanistan,33.939110,67.709953,0,0,0,0,0,0,...,27166,27166,27166,27166,27681,28016,28016,28180,28360,Afghanistan
1,NaN,Albania,41.153300,20.168300,0,0,0,0,0,0,...,3794,3816,3871,3928,3986,4096,4184,4332,4413,Albania
2,NaN,Algeria,28.033900,1.659600,0,0,0,0,0,0,...,27017,27347,27653,27971,28281,28587,28874,29142,29369,Algeria
3,NaN,Andorra,42.506300,1.521800,0,0,0,0,0,0,...,863,869,869,875,875,875,875,875,877,Andorra
4,NaN,Angola,-11.202700,17.873900,0,0,0,0,0,0,...,628,632,667,698,742,804,814,818,877,Angola
5,NaN,Antigua and Barbuda,17.060800,-61.796400,0,0,0,0,0,0,...,88,88,88,88,89,89,89,89,89,Antigua and Barbuda
6,NaN,Argentina,-38.416100,-63.616700,0,0,0,0,0,0,...,211702,217850,223531,228725,233651,239806,245781,251400,256789,Argentina
7,NaN,Armenia,40.069100,45.038200,0,0,0,0,0,0,...,34584,34655,34982,35226,35476,35693,35907,35991,36049,Armenia
8,Australian Capital Territory,Australia,-35.473500,149.012400,0,0,0,0,0,0,...,110,110,110,110,110,110,110,110,110,AustraliaAustralian Capital Territory
9,New South Wales,Australia,-33.868800,151.209300,0,0,0,0,0,0,...,2994,2994,2994,2995,2994,2994,2994,2994,2994,AustraliaNew South Wales
10,Northern Territory,Australia,-12.463400,130.845600,0,0,0,0,0,0,...,31,31,31,31,31,31,31,31,31,AustraliaNorthern Territory
11,Queensland,Australia,-27.469800,153.025100,0,0,0,0,0,0,...,1079,1079,1079,1081,1082,1082,1082,1082,1082,AustraliaQueensland
12,South Australia,Australia,-34.928500,138.600700,0,0,0,0,0,0,...,450,450,451,452,452,452,452,456,456,AustraliaSouth Australia
13,Tasmania,Australia,-42.882100,147.327200,0,0,0,0,0,0,...,216,216,216,216,216,216,216,216,216,AustraliaTasmania
14,Victoria,Australia,-37.813600,144.963100,0,0,0,0,0,0,...,8570,9023,9413,9729,12334,12940,13239,13708,14077,AustraliaVictoria
15,Western Australia,Australia,-31.950500,115.860500,0,0,0,0,0,0,...,633,633,633,633,633,633,634,634,635,AustraliaWestern Australia
16,NaN,Austria,47.516200,14.550100,0,0,0,0,0,0,...,20681,20765,20870,20958,21093,21260,21406,21558,21657,Austria
17,NaN,Azerbaijan,40.143100,47.576900,0,0,0,0,0,0,...,31875,32042,32201,32363,32511,32682,32842,32993,33104,Azerbaijan
18,NaN,Bahamas,25.025885,-78.035889,0,0,0,0,0,0,...,189,191,203,209,211,221,221,227,227,Bahamas
19,NaN,Bahrain,26.027500,50.550000,0,0,0,0,0,0,...,43128,43529,43921,44278,44628,45166,45589,45981,46311,Bahrain
20,NaN,Bangladesh,23.685000,90.356300,0,0,0,0,0,0,...,158950,160591,162825,165738,168991,172615,175567,179091,182875,Bangladesh
21,NaN,Barbados,13.193900,-59.543200,0,0,0,0,0,0,...,122,122,122,123,123,124,126,132,132,Barbados
22,NaN,Belarus,53.709800,27.953400,0,0,0,0,0,0,...,67072,67149,67339,67647,67929,68256,68577,68839,68925,Belarus
23,NaN,Belgium,50.833300,4.469936,0,0,0,0,0,0,...,17994,18003,18048,18078,18131,18165,18204,18225,18242,Belgium
24,NaN,Belize,17.189900,-88.497600,0,0,0,0,0,0,...,35,38,38,38,38,43,44,44,45,Belize
25,NaN,Benin,9.307700,2.315800,0,0,0,0,0,0,...,1690,1690,1690,1690,1705,1705,1705,1705,1705,Benin
26,NaN,Bhutan,27.514200,90.433600,0,0,0,0,0,0,...,102,103,103,103,108,110,112,112,117,Bhutan
27,NaN,Bolivia,-16.290200,-63.588700,0,0,0,0,0,0,...,36491,37471,38623,39965,41111,42141,43887,45396,47050,Bolivia
28,NaN,Bosnia and Herzegovina,43.915900,17.679100,0,0,0,0,0,0,...,9619,9856,10279,10711,10881,11157,11329,11329,11861,Bosnia and Herzegovina
29,NaN,Botswana,-22.328500,24.684900,0,0,0,0,0,0,...,120,136,136,136,136,136,136,136,199,Botswana
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
223,NaN,Thailand,15.870032,100.992541,0,0,0,0,2,2,...,3194,3194,3199,3199,3218,3219,3220,3221,3229,Thailand
224,NaN,Timor-Leste,-8.874200,125.727500,0,0,0,0,0,0,...,24,24,24,25,25,25,25,25,25,Timor-Leste
225,NaN,Togo,8.619500,0.824800,0,0,0,0,0,0,...,843,858,868,875,878,891,903,910,914,Togo
226,NaN,Trinidad and Tobago,10.691800,-61.222500,0,0,0,0,0,0,...,140,140,140,140,140,162,165,165,165,Trinidad and Tobago
227,NaN,Tunisia,33.886917,9.537499,0,0,0,0,0,0,...,1358,1362,1370,1395,1397,1420,1434,1443,1454,Tunisia
228,NaN,Turkey,38.963700,35.243300,0,0,0,0,0,0,...,230969,231971,232913,233915,234797,235569,236370,237165,237908,Turkey
229,NaN,US,40.000000,-100.000000,0,0,0,0,0,0,...,1833067,1865580,1898159,1925049,1947035,1965056,1985484,1997761,2020774,US
230,NaN,Uganda,1.373333,32.290275,0,0,0,0,0,0,...,1142,1165,1165,1188,1194,1199,1199,1199,1248,Uganda
231,NaN,Ukraine,48.379400,31.165600,0,0,0,0,0,0,...,49346,49692,50508,51358,52086,52769,53458,53968,54262,Ukraine
232,NaN,United Arab Emirates,23.424076,53.847818,0,0,0,0,0,0,...,57694,57794,57909,58022,58153,58296,58408,58488,58582,United Arab Emirates
233,Anguilla,United Kingdom,18.220600,-63.068600,0,0,0,0,0,0,...,3,3,3,3,3,3,3,3,3,United KingdomAnguilla
234,Bermuda,United Kingdom,32.307800,-64.750500,0,0,0,0,0,0,...,147,147,147,147,147,147,149,149,150,United KingdomBermuda
235,British Virgin Islands,United Kingdom,18.420700,-64.640000,0,0,0,0,0,0,...,7,7,8,8,8,8,8,8,8,United KingdomBritish Virgin Islands
236,Cayman Islands,United Kingdom,19.313300,-81.254600,0,0,0,0,0,0,...,202,202,202,202,202,202,202,202,202,United KingdomCayman Islands
237,Channel Islands,United Kingdom,49.372300,-2.364400,0,0,0,0,0,0,...,545,545,545,545,545,545,545,545,545,United KingdomChannel Islands
238,Falkland Islands (Malvinas),United Kingdom,-51.796300,-59.523600,0,0,0,0,0,0,...,13,13,13,13,13,13,13,13,13,United KingdomFalkland Islands (Malvinas)
239,Gibraltar,United Kingdom,36.140800,-5.353600,0,0,0,0,0,0,...,190,194,195,197,200,200,201,201,203,United KingdomGibraltar
240,Isle of Man,United Kingdom,54.236100,-4.548100,0,0,0,0,0,0,...,312,312,312,312,312,312,312,312,312,United KingdomIsle of Man
241,Montserrat,United Kingdom,16.742498,-62.187366,0,0,0,0,0,0,...,12,12,12,12,12,12,12,12,12,United KingdomMontserrat
242,Turks and Caicos Islands,United Kingdom,21.694000,-71.797900,0,0,0,0,0,0,...,55,55,56,56,102,102,102,102,102,United KingdomTurks and Caicos Islands
243,NaN,United Kingdom,55.378100,-3.436000,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,United Kingdom
244,NaN,Uruguay,-32.522800,-55.765800,0,0,0,0,0,0,...,1200,1205,1219,1228,1242,1249,1264,1276,1295,Uruguay
245,NaN,Uzbekistan,41.377491,64.585262,0,0,0,0,0,0,...,30973,30973,32062,32944,33261,33989,34576,34987,35551,Uzbekistan
246,NaN,Venezuela,6.423800,-66.589700,0,0,0,0,0,0,...,22700,23575,24561,25416,26330,27306,28453,29966,31080,Venezuela
247,NaN,Vietnam,14.058324,108.277199,0,0,0,0,0,0,...,456,467,526,533,542,545,563,568,587,Vietnam
248,NaN,West Bank and Gaza,31.952200,35.233200,0,0,0,0,0,0,...,9838,9906,9939,10312,10682,11102,11103,11843,11870,West Bank and Gaza
249,NaN,Western Sahara,24.215500,-12.885800,0,0,0,0,0,0,...,8,8,8,8,8,8,8,8,8,Western Sahara
250,NaN,Yemen,15.552727,48.516388,0,0,0,0,0,0,...,1013,1045,1052,1055,1058,1058,1066,1086,1090,Yemen
251,NaN,Zambia,-13.133897,27.849332,0,0,0,0,0,0,...,8412,8575,8776,9126,9126,9126,9942,9942,10208,Zambia
252,NaN,Zimbabwe,-19.015438,29.154857,0,0,0,0,0,0,...,2092,3848,4105,4442,4525,4587,4629,4872,4950,Zimbabwe

In [17]:
uniqueCOuntryName=pd.unique(confirmedGlobal['Country/Region'])
df2=confirmedGlobal[list(confirmedGlobal.columns[1:2])+list([confirmedGlobal.columns[-2]])]
df2.columns=['Country','values']
dictVal=[]
for i in range(df2.shape[0]):
    dictVal.append(dict(df2.ix[i]))
df2=df2.sort_values(by='values',ascending=False)
contryNames=list(df2['Country'].values)
(df2.head())

          Country   values
242            US  5739724
30         Brazil  3622861
143         India  3167323
208        Russia   959016
224  South Africa   611450

In [22]:
import dateutil
timestamps=[dateutil.parser.parse(i) for i in confirmedGlobal.columns[4:-1]]
datasetsForLine=[]
for i in uniqueCOuntryName:
    temp={}
    temp['label']=i
    temp['data']=confirmedGlobal[confirmedGlobal['Country/Region']==i][confirmedGlobal.columns[4:-1]].sum().values.tolist()
    datasetsForLine.append(temp)

In [23]:
df3=pd.read_json('https://cdn.jsdelivr.net/gh/highcharts/highcharts@v7.0.0/samples/data/world-population-density.json')
df3.head()

  code code3         name   value
0   AW   ABW        Aruba  582.34
1   AF   AFG  Afghanistan   53.08
2   AO   AGO       Angola   23.11
3   AL   ALB      Albania  104.97
4   AD   AND      Andorra  164.43

In [24]:
dataForMap=[]
for i in uniqueCOuntryName:
    try:
        tempdf=df3[df3['name']==i]
        temp={}
        temp["code3"]=list(tempdf['code3'].values)[0]
        temp["name"]=i
        temp["value"]=df2[df2['Country']==i]['values'].sum()
        temp["code"]=list(tempdf['code'].values)[0]
        dataForMap.append(temp)
    except:
        pass

In [25]:
dataForMap

[{'code3': 'AFG', 'name': 'Afghanistan', 'value': 38054, 'code': 'AF'},
 {'code3': 'ALB', 'name': 'Albania', 'value': 8605, 'code': 'AL'},
 {'code3': 'DZA', 'name': 'Algeria', 'value': 41858, 'code': 'DZ'},
 {'code3': 'AND', 'name': 'Andorra', 'value': 1060, 'code': 'AD'},
 {'code3': 'AGO', 'name': 'Angola', 'value': 2222, 'code': 'AO'},
 {'code3': 'ATG', 'name': 'Antigua and Barbuda', 'value': 94, 'code': 'AG'},
 {'code3': 'ARG', 'name': 'Argentina', 'value': 350867, 'code': 'AR'},
 {'code3': 'ARM', 'name': 'Armenia', 'value': 42825, 'code': 'AM'},
 {'code3': 'AUS', 'name': 'Australia', 'value': 25053, 'code': 'AU'},
 {'code3': 'AUT', 'name': 'Austria', 'value': 25495, 'code': 'AT'},
 {'code3': 'AZE', 'name': 'Azerbaijan', 'value': 35426, 'code': 'AZ'},
 {'code3': 'BHR', 'name': 'Bahrain', 'value': 49719, 'code': 'BH'},
 {'code3': 'BGD', 'name': 'Bangladesh', 'value': 297083, 'code': 'BD'},
 {'code3': 'BRB', 'name': 'Barbados', 'value': 161, 'code': 'BB'},
 {'code3': 'BLR', 'name': 'Belarus', 'value': 70645, 'code': 'BY'},
 {'code3': 'BEL', 'name': 'Belgium', 'value': 82092, 'code': 'BE'},
 {'code3': 'BLZ', 'name': 'Belize', 'value': 713, 'code': 'BZ'},
 {'code3': 'BEN', 'name': 'Benin', 'value': 2115, 'code': 'BJ'},
 {'code3': 'BTN', 'name': 'Bhutan', 'value': 156, 'code': 'BT'},
 {'code3': 'BOL', 'name': 'Bolivia', 'value': 110148, 'code': 'BO'},
 {'code3': 'BIH',
  'name': 'Bosnia and Herzegovina',
  'value': 18029,
  'code': 'BA'},
 {'code3': 'BWA', 'name': 'Botswana', 'value': 1562, 'code': 'BW'},
 {'code3': 'BRA', 'name': 'Brazil', 'value': 3622861, 'code': 'BR'},
 {'code3': 'BGR', 'name': 'Bulgaria', 'value': 15386, 'code': 'BG'},
 {'code3': 'BFA', 'name': 'Burkina Faso', 'value': 1338, 'code': 'BF'},
 {'code3': 'BDI', 'name': 'Burundi', 'value': 430, 'code': 'BI'},
 {'code3': 'CPV', 'name': 'Cabo Verde', 'value': 3532, 'code': 'CV'},
 {'code3': 'KHM', 'name': 'Cambodia', 'value': 273, 'code': 'KH'},
 {'code3': 'CMR', 'name': 'Cameroon', 'value': 18762, 'code': 'CM'},
 {'code3': 'CAN', 'name': 'Canada', 'value': 127594, 'code': 'CA'},
 {'code3': 'CAF',
  'name': 'Central African Republic',
  'value': 4679,
  'code': 'CF'},
 {'code3': 'TCD', 'name': 'Chad', 'value': 987, 'code': 'TD'},
 {'code3': 'CHL', 'name': 'Chile', 'value': 399568, 'code': 'CL'},
 {'code3': 'CHN', 'name': 'China', 'value': 89718, 'code': 'CN'},
 {'code3': 'COL', 'name': 'Colombia', 'value': 551688, 'code': 'CO'},
 {'code3': 'COM', 'name': 'Comoros', 'value': 417, 'code': 'KM'},
 {'code3': 'CRI', 'name': 'Costa Rica', 'value': 34463, 'code': 'CR'},
 {'code3': 'CIV', 'name': "Cote d'Ivoire", 'value': 17506, 'code': 'CI'},
 {'code3': 'HRV', 'name': 'Croatia', 'value': 8311, 'code': 'HR'},
 {'code3': 'CUB', 'name': 'Cuba', 'value': 3717, 'code': 'CU'},
 {'code3': 'CYP', 'name': 'Cyprus', 'value': 1451, 'code': 'CY'},
 {'code3': 'DNK', 'name': 'Denmark', 'value': 16821, 'code': 'DK'},
 {'code3': 'DJI', 'name': 'Djibouti', 'value': 5383, 'code': 'DJ'},
 {'code3': 'DMA', 'name': 'Dominica', 'value': 20, 'code': 'DM'},
 {'code3': 'DOM', 'name': 'Dominican Republic', 'value': 91608, 'code': 'DO'},
 {'code3': 'ECU', 'name': 'Ecuador', 'value': 108289, 'code': 'EC'},
 {'code3': 'SLV', 'name': 'El Salvador', 'value': 24811, 'code': 'SV'},
 {'code3': 'GNQ', 'name': 'Equatorial Guinea', 'value': 4926, 'code': 'GQ'},
 {'code3': 'EST', 'name': 'Estonia', 'value': 2275, 'code': 'EE'},
 {'code3': 'ETH', 'name': 'Ethiopia', 'value': 42143, 'code': 'ET'},
 {'code3': 'FJI', 'name': 'Fiji', 'value': 28, 'code': 'FJ'},
 {'code3': 'FIN', 'name': 'Finland', 'value': 7938, 'code': 'FI'},
 {'code3': 'FRA', 'name': 'France', 'value': 282414, 'code': 'FR'},
 {'code3': 'GAB', 'name': 'Gabon', 'value': 8409, 'code': 'GA'},
 {'code3': 'GEO', 'name': 'Georgia', 'value': 1421, 'code': 'GE'},
 {'code3': 'DEU', 'name': 'Germany', 'value': 236122, 'code': 'DE'},
 {'code3': 'GHA', 'name': 'Ghana', 'value': 43622, 'code': 'GH'},
 {'code3': 'GRC', 'name': 'Greece', 'value': 8819, 'code': 'GR'},
 {'code3': 'GRD', 'name': 'Grenada', 'value': 24, 'code': 'GD'},
 {'code3': 'GTM', 'name': 'Guatemala', 'value': 68533, 'code': 'GT'},
 {'code3': 'GIN', 'name': 'Guinea', 'value': 9076, 'code': 'GN'},
 {'code3': 'GNB', 'name': 'Guinea-Bissau', 'value': 2149, 'code': 'GW'},
 {'code3': 'GUY', 'name': 'Guyana', 'value': 1029, 'code': 'GY'},
 {'code3': 'HTI', 'name': 'Haiti', 'value': 8110, 'code': 'HT'},
 {'code3': 'HND', 'name': 'Honduras', 'value': 55479, 'code': 'HN'},
 {'code3': 'HUN', 'name': 'Hungary', 'value': 5191, 'code': 'HU'},
 {'code3': 'ISL', 'name': 'Iceland', 'value': 2073, 'code': 'IS'},
 {'code3': 'IND', 'name': 'India', 'value': 3167323, 'code': 'IN'},
 {'code3': 'IDN', 'name': 'Indonesia', 'value': 155412, 'code': 'ID'},
 {'code3': 'IRQ', 'name': 'Iraq', 'value': 207985, 'code': 'IQ'},
 {'code3': 'IRL', 'name': 'Ireland', 'value': 28116, 'code': 'IE'},
 {'code3': 'ISR', 'name': 'Israel', 'value': 104472, 'code': 'IL'},
 {'code3': 'ITA', 'name': 'Italy', 'value': 260298, 'code': 'IT'},
 {'code3': 'JAM', 'name': 'Jamaica', 'value': 1612, 'code': 'JM'},
 {'code3': 'JPN', 'name': 'Japan', 'value': 63158, 'code': 'JP'},
 {'code3': 'JOR', 'name': 'Jordan', 'value': 1639, 'code': 'JO'},
 {'code3': 'KAZ', 'name': 'Kazakhstan', 'value': 104902, 'code': 'KZ'},
 {'code3': 'KEN', 'name': 'Kenya', 'value': 32557, 'code': 'KE'},
 {'code3': 'KWT', 'name': 'Kuwait', 'value': 80960, 'code': 'KW'},
 {'code3': 'LVA', 'name': 'Latvia', 'value': 1337, 'code': 'LV'},
 {'code3': 'LBN', 'name': 'Lebanon', 'value': 13155, 'code': 'LB'},
 {'code3': 'LSO', 'name': 'Lesotho', 'value': 1015, 'code': 'LS'},
 {'code3': 'LBR', 'name': 'Liberia', 'value': 1290, 'code': 'LR'},
 {'code3': 'LBY', 'name': 'Libya', 'value': 11009, 'code': 'LY'},
 {'code3': 'LIE', 'name': 'Liechtenstein', 'value': 100, 'code': 'LI'},
 {'code3': 'LTU', 'name': 'Lithuania', 'value': 2673, 'code': 'LT'},
 {'code3': 'LUX', 'name': 'Luxembourg', 'value': 7794, 'code': 'LU'},
 {'code3': 'MDG', 'name': 'Madagascar', 'value': 14402, 'code': 'MG'},
 {'code3': 'MWI', 'name': 'Malawi', 'value': 5419, 'code': 'MW'},
 {'code3': 'MYS', 'name': 'Malaysia', 'value': 9274, 'code': 'MY'},
 {'code3': 'MDV', 'name': 'Maldives', 'value': 6912, 'code': 'MV'},
 {'code3': 'MLI', 'name': 'Mali', 'value': 2708, 'code': 'ML'},
 {'code3': 'MLT', 'name': 'Malta', 'value': 1667, 'code': 'MT'},
 {'code3': 'MRT', 'name': 'Mauritania', 'value': 6928, 'code': 'MR'},
 {'code3': 'MUS', 'name': 'Mauritius', 'value': 347, 'code': 'MU'},
 {'code3': 'MEX', 'name': 'Mexico', 'value': 563705, 'code': 'MX'},
 {'code3': 'MDA', 'name': 'Moldova', 'value': 33828, 'code': 'MD'},
 {'code3': 'MCO', 'name': 'Monaco', 'value': 154, 'code': 'MC'},
 {'code3': 'MNG', 'name': 'Mongolia', 'value': 298, 'code': 'MN'},
 {'code3': 'MNE', 'name': 'Montenegro', 'value': 4378, 'code': 'ME'},
 {'code3': 'MAR', 'name': 'Morocco', 'value': 53252, 'code': 'MA'},
 {'code3': 'MOZ', 'name': 'Mozambique', 'value': 3440, 'code': 'MZ'},
 {'code3': 'NAM', 'name': 'Namibia', 'value': 6030, 'code': 'NA'},
 {'code3': 'NPL', 'name': 'Nepal', 'value': 32678, 'code': 'NP'},
 {'code3': 'NLD', 'name': 'Netherlands', 'value': 69224, 'code': 'NL'},
 {'code3': 'NZL', 'name': 'New Zealand', 'value': 1690, 'code': 'NZ'},
 {'code3': 'NIC', 'name': 'Nicaragua', 'value': 4311, 'code': 'NI'},
 {'code3': 'NER', 'name': 'Niger', 'value': 1172, 'code': 'NE'},
 {'code3': 'NGA', 'name': 'Nigeria', 'value': 52548, 'code': 'NG'},
 {'code3': 'NOR', 'name': 'Norway', 'value': 10395, 'code': 'NO'},
 {'code3': 'OMN', 'name': 'Oman', 'value': 84509, 'code': 'OM'},
 {'code3': 'PAK', 'name': 'Pakistan', 'value': 293261, 'code': 'PK'},
 {'code3': 'PAN', 'name': 'Panama', 'value': 87485, 'code': 'PA'},
 {'code3': 'PNG', 'name': 'Papua New Guinea', 'value': 401, 'code': 'PG'},
 {'code3': 'PRY', 'name': 'Paraguay', 'value': 13602, 'code': 'PY'},
 {'code3': 'PER', 'name': 'Peru', 'value': 594326, 'code': 'PE'},
 {'code3': 'PHL', 'name': 'Philippines', 'value': 194252, 'code': 'PH'},
 {'code3': 'POL', 'name': 'Poland', 'value': 62310, 'code': 'PL'},
 {'code3': 'PRT', 'name': 'Portugal', 'value': 55720, 'code': 'PT'},
 {'code3': 'QAT', 'name': 'Qatar', 'value': 117266, 'code': 'QA'},
 {'code3': 'ROU', 'name': 'Romania', 'value': 79330, 'code': 'RO'},
 {'code3': 'RWA', 'name': 'Rwanda', 'value': 3306, 'code': 'RW'},
 {'code3': 'SMR', 'name': 'San Marino', 'value': 704, 'code': 'SM'},
 {'code3': 'STP', 'name': 'Sao Tome and Principe', 'value': 892, 'code': 'ST'},
 {'code3': 'SAU', 'name': 'Saudi Arabia', 'value': 308654, 'code': 'SA'},
 {'code3': 'SEN', 'name': 'Senegal', 'value': 13013, 'code': 'SN'},
 {'code3': 'SRB', 'name': 'Serbia', 'value': 30714, 'code': 'RS'},
 {'code3': 'SYC', 'name': 'Seychelles', 'value': 132, 'code': 'SC'},
 {'code3': 'SLE', 'name': 'Sierra Leone', 'value': 1997, 'code': 'SL'},
 {'code3': 'SGP', 'name': 'Singapore', 'value': 56404, 'code': 'SG'},
 {'code3': 'SVN', 'name': 'Slovenia', 'value': 2665, 'code': 'SI'},
 {'code3': 'SOM', 'name': 'Somalia', 'value': 3269, 'code': 'SO'},
 {'code3': 'ZAF', 'name': 'South Africa', 'value': 611450, 'code': 'ZA'},
 {'code3': 'ESP', 'name': 'Spain', 'value': 405436, 'code': 'ES'},
 {'code3': 'LKA', 'name': 'Sri Lanka', 'value': 2959, 'code': 'LK'},
 {'code3': 'SDN', 'name': 'Sudan', 'value': 12903, 'code': 'SD'},
 {'code3': 'SUR', 'name': 'Suriname', 'value': 3632, 'code': 'SR'},
 {'code3': 'SWE', 'name': 'Sweden', 'value': 86721, 'code': 'SE'},
 {'code3': 'CHE', 'name': 'Switzerland', 'value': 40060, 'code': 'CH'},
 {'code3': 'TJK', 'name': 'Tajikistan', 'value': 8346, 'code': 'TJ'},
 {'code3': 'TZA', 'name': 'Tanzania', 'value': 509, 'code': 'TZ'},
 {'code3': 'THA', 'name': 'Thailand', 'value': 3402, 'code': 'TH'},
 {'code3': 'TLS', 'name': 'Timor-Leste', 'value': 26, 'code': 'TL'},
 {'code3': 'TGO', 'name': 'Togo', 'value': 1295, 'code': 'TG'},
 {'code3': 'TTO', 'name': 'Trinidad and Tobago', 'value': 1099, 'code': 'TT'},
 {'code3': 'TUN', 'name': 'Tunisia', 'value': 2893, 'code': 'TN'},
 {'code3': 'TUR', 'name': 'Turkey', 'value': 259692, 'code': 'TR'},
 {'code3': 'UGA', 'name': 'Uganda', 'value': 2362, 'code': 'UG'},
 {'code3': 'UKR', 'name': 'Ukraine', 'value': 109234, 'code': 'UA'},
 {'code3': 'ARE',
  'name': 'United Arab Emirates',
  'value': 67282,
  'code': 'AE'},
 {'code3': 'GBR', 'name': 'United Kingdom', 'value': 328620, 'code': 'GB'},
 {'code3': 'URY', 'name': 'Uruguay', 'value': 1533, 'code': 'UY'},
 {'code3': 'UZB', 'name': 'Uzbekistan', 'value': 39348, 'code': 'UZ'},
 {'code3': 'VNM', 'name': 'Vietnam', 'value': 1022, 'code': 'VN'},
 {'code3': 'PSE', 'name': 'West Bank and Gaza', 'value': 19213, 'code': 'PS'},
 {'code3': 'ZMB', 'name': 'Zambia', 'value': 11148, 'code': 'ZM'},
 {'code3': 'ZWE', 'name': 'Zimbabwe', 'value': 6070, 'code': 'ZW'}]

In [26]:
df3=confirmedGlobal[list(confirmedGlobal.columns[1:2])+list(list(confirmedGlobal.columns.values)[-6:-1])]
df3.head()

  Country/Region  8/20/20  8/21/20  8/22/20  8/23/20  8/24/20
0    Afghanistan    37856    37894    37953    37999    38054
1        Albania     7967     8119     8275     8427     8605
2        Algeria    40258    40667    41068    41460    41858
3        Andorra     1024     1045     1045     1045     1060
4         Angola     2044     2068     2134     2171     2222

In [27]:
dataForheatMap=[]
for i in contryNames:
    try:
        tempdf=df3[df3['Country/Region']==i]
        temp={}
        temp["name"]=i
        temp["data"]=[{'x':j,'y':k} for j,k in zip(tempdf[tempdf.columns[1:]].sum().index,tempdf[tempdf.columns[1:]].sum().values)]
        dataForheatMap.append(temp)
    except:
        pass
dataForheatMap

[{'name': 'US',
  'data': [{'x': '8/20/20', 'y': 5573847},
   {'x': '8/21/20', 'y': 5622540},
   {'x': '8/22/20', 'y': 5667112},
   {'x': '8/23/20', 'y': 5701679},
   {'x': '8/24/20', 'y': 5739724}]},
 {'name': 'Brazil',
  'data': [{'x': '8/20/20', 'y': 3501975},
   {'x': '8/21/20', 'y': 3532330},
   {'x': '8/22/20', 'y': 3582362},
   {'x': '8/23/20', 'y': 3605783},
   {'x': '8/24/20', 'y': 3622861}]},
 {'name': 'India',
  'data': [{'x': '8/20/20', 'y': 2905825},
   {'x': '8/21/20', 'y': 2975701},
   {'x': '8/22/20', 'y': 3044940},
   {'x': '8/23/20', 'y': 3106348},
   {'x': '8/24/20', 'y': 3167323}]},
 {'name': 'Russia',
  'data': [{'x': '8/20/20', 'y': 939833},
   {'x': '8/21/20', 'y': 944671},
   {'x': '8/22/20', 'y': 949531},
   {'x': '8/23/20', 'y': 954328},
   {'x': '8/24/20', 'y': 959016}]},
 {'name': 'South Africa',
  'data': [{'x': '8/20/20', 'y': 599940},
   {'x': '8/21/20', 'y': 603338},
   {'x': '8/22/20', 'y': 607045},
   {'x': '8/23/20', 'y': 609773},
   {'x': '8/24/20', 'y': 611450}]},
 {'name': 'Peru',
  'data': [{'x': '8/20/20', 'y': 558420},
   {'x': '8/21/20', 'y': 567059},
   {'x': '8/22/20', 'y': 576067},
   {'x': '8/23/20', 'y': 585236},
   {'x': '8/24/20', 'y': 594326}]},
 {'name': 'Mexico',
  'data': [{'x': '8/20/20', 'y': 543806},
   {'x': '8/21/20', 'y': 549734},
   {'x': '8/22/20', 'y': 556216},
   {'x': '8/23/20', 'y': 560164},
   {'x': '8/24/20', 'y': 563705}]},
 {'name': 'Colombia',
  'data': [{'x': '8/20/20', 'y': 513719},
   {'x': '8/21/20', 'y': 522138},
   {'x': '8/22/20', 'y': 522138},
   {'x': '8/23/20', 'y': 541139},
   {'x': '8/24/20', 'y': 551688}]},
 {'name': 'Spain',
  'data': [{'x': '8/20/20', 'y': 377906},
   {'x': '8/21/20', 'y': 386054},
   {'x': '8/22/20', 'y': 386054},
   {'x': '8/23/20', 'y': 386054},
   {'x': '8/24/20', 'y': 405436}]},
 {'name': 'Chile',
  'data': [{'x': '8/20/20', 'y': 391849},
   {'x': '8/21/20', 'y': 393769},
   {'x': '8/22/20', 'y': 395708},
   {'x': '8/23/20', 'y': 397665},
   {'x': '8/24/20', 'y': 399568}]},
 {'name': 'Iran',
  'data': [{'x': '8/20/20', 'y': 352558},
   {'x': '8/21/20', 'y': 354764},
   {'x': '8/22/20', 'y': 356792},
   {'x': '8/23/20', 'y': 358905},
   {'x': '8/24/20', 'y': 361150}]},
 {'name': 'Argentina',
  'data': [{'x': '8/20/20', 'y': 320884},
   {'x': '8/21/20', 'y': 329043},
   {'x': '8/22/20', 'y': 336802},
   {'x': '8/23/20', 'y': 342154},
   {'x': '8/24/20', 'y': 350867}]},
 {'name': 'United Kingdom',
  'data': [{'x': '8/20/20', 'y': 324203},
   {'x': '8/21/20', 'y': 325263},
   {'x': '8/22/20', 'y': 326595},
   {'x': '8/23/20', 'y': 327643},
   {'x': '8/24/20', 'y': 328620}]},
 {'name': 'Saudi Arabia',
  'data': [{'x': '8/20/20', 'y': 303973},
   {'x': '8/21/20', 'y': 305186},
   {'x': '8/22/20', 'y': 306370},
   {'x': '8/23/20', 'y': 307479},
   {'x': '8/24/20', 'y': 308654}]},
 {'name': 'Bangladesh',
  'data': [{'x': '8/20/20', 'y': 287959},
   {'x': '8/21/20', 'y': 290360},
   {'x': '8/22/20', 'y': 292625},
   {'x': '8/23/20', 'y': 294598},
   {'x': '8/24/20', 'y': 297083}]},
 {'name': 'Pakistan',
  'data': [{'x': '8/20/20', 'y': 290958},
   {'x': '8/21/20', 'y': 291588},
   {'x': '8/22/20', 'y': 292174},
   {'x': '8/23/20', 'y': 293261},
   {'x': '8/24/20', 'y': 293261}]},
 {'name': 'France',
  'data': [{'x': '8/20/20', 'y': 256534},
   {'x': '8/21/20', 'y': 271960},
   {'x': '8/22/20', 'y': 275562},
   {'x': '8/23/20', 'y': 280459},
   {'x': '8/24/20', 'y': 282414}]},
 {'name': 'Italy',
  'data': [{'x': '8/20/20', 'y': 256118},
   {'x': '8/21/20', 'y': 257065},
   {'x': '8/22/20', 'y': 258136},
   {'x': '8/23/20', 'y': 259345},
   {'x': '8/24/20', 'y': 260298}]},
 {'name': 'Turkey',
  'data': [{'x': '8/20/20', 'y': 254520},
   {'x': '8/21/20', 'y': 255723},
   {'x': '8/22/20', 'y': 257032},
   {'x': '8/23/20', 'y': 258249},
   {'x': '8/24/20', 'y': 259692}]},
 {'name': 'Germany',
  'data': [{'x': '8/20/20', 'y': 231292},
   {'x': '8/21/20', 'y': 233029},
   {'x': '8/22/20', 'y': 233861},
   {'x': '8/23/20', 'y': 234494},
   {'x': '8/24/20', 'y': 236122}]},
 {'name': 'Iraq',
  'data': [{'x': '8/20/20', 'y': 192797},
   {'x': '8/21/20', 'y': 197085},
   {'x': '8/22/20', 'y': 201050},
   {'x': '8/23/20', 'y': 204341},
   {'x': '8/24/20', 'y': 207985}]},
 {'name': 'Philippines',
  'data': [{'x': '8/20/20', 'y': 178022},
   {'x': '8/21/20', 'y': 182365},
   {'x': '8/22/20', 'y': 187249},
   {'x': '8/23/20', 'y': 189601},
   {'x': '8/24/20', 'y': 194252}]},
 {'name': 'Indonesia',
  'data': [{'x': '8/20/20', 'y': 147211},
   {'x': '8/21/20', 'y': 149408},
   {'x': '8/22/20', 'y': 151498},
   {'x': '8/23/20', 'y': 153535},
   {'x': '8/24/20', 'y': 155412}]},
 {'name': 'Qatar',
  'data': [{'x': '8/20/20', 'y': 116224},
   {'x': '8/21/20', 'y': 116481},
   {'x': '8/22/20', 'y': 116765},
   {'x': '8/23/20', 'y': 117008},
   {'x': '8/24/20', 'y': 117266}]},
 {'name': 'Bolivia',
  'data': [{'x': '8/20/20', 'y': 106065},
   {'x': '8/21/20', 'y': 107435},
   {'x': '8/22/20', 'y': 108427},
   {'x': '8/23/20', 'y': 109149},
   {'x': '8/24/20', 'y': 110148}]},
 {'name': 'Ukraine',
  'data': [{'x': '8/20/20', 'y': 100810},
   {'x': '8/21/20', 'y': 102948},
   {'x': '8/22/20', 'y': 105337},
   {'x': '8/23/20', 'y': 107379},
   {'x': '8/24/20', 'y': 109234}]},
 {'name': 'Ecuador',
  'data': [{'x': '8/20/20', 'y': 105508},
   {'x': '8/21/20', 'y': 106481},
   {'x': '8/22/20', 'y': 107089},
   {'x': '8/23/20', 'y': 107769},
   {'x': '8/24/20', 'y': 108289}]},
 {'name': 'Kazakhstan',
  'data': [{'x': '8/20/20', 'y': 104071},
   {'x': '8/21/20', 'y': 104313},
   {'x': '8/22/20', 'y': 104543},
   {'x': '8/23/20', 'y': 104718},
   {'x': '8/24/20', 'y': 104902}]},
 {'name': 'Israel',
  'data': [{'x': '8/20/20', 'y': 99599},
   {'x': '8/21/20', 'y': 100716},
   {'x': '8/22/20', 'y': 101933},
   {'x': '8/23/20', 'y': 102663},
   {'x': '8/24/20', 'y': 104472}]},
 {'name': 'Egypt',
  'data': [{'x': '8/20/20', 'y': 97025},
   {'x': '8/21/20', 'y': 97148},
   {'x': '8/22/20', 'y': 97237},
   {'x': '8/23/20', 'y': 97340},
   {'x': '8/24/20', 'y': 97478}]},
 {'name': 'Dominican Republic',
  'data': [{'x': '8/20/20', 'y': 89010},
   {'x': '8/21/20', 'y': 89867},
   {'x': '8/22/20', 'y': 90561},
   {'x': '8/23/20', 'y': 91161},
   {'x': '8/24/20', 'y': 91608}]},
 {'name': 'Panama',
  'data': [{'x': '8/20/20', 'y': 83855},
   {'x': '8/21/20', 'y': 84392},
   {'x': '8/22/20', 'y': 85480},
   {'x': '8/23/20', 'y': 86900},
   {'x': '8/24/20', 'y': 87485}]},
 {'name': 'Sweden',
  'data': [{'x': '8/20/20', 'y': 85810},
   {'x': '8/21/20', 'y': 86068},
   {'x': '8/22/20', 'y': 86068},
   {'x': '8/23/20', 'y': 86068},
   {'x': '8/24/20', 'y': 86721}]},
 {'name': 'Oman',
  'data': [{'x': '8/20/20', 'y': 83769},
   {'x': '8/21/20', 'y': 83769},
   {'x': '8/22/20', 'y': 83769},
   {'x': '8/23/20', 'y': 83769},
   {'x': '8/24/20', 'y': 84509}]},
 {'name': 'Belgium',
  'data': [{'x': '8/20/20', 'y': 80178},
   {'x': '8/21/20', 'y': 80894},
   {'x': '8/22/20', 'y': 81468},
   {'x': '8/23/20', 'y': 81936},
   {'x': '8/24/20', 'y': 82092}]},
 {'name': 'Kuwait',
  'data': [{'x': '8/20/20', 'y': 78767},
   {'x': '8/21/20', 'y': 79269},
   {'x': '8/22/20', 'y': 79957},
   {'x': '8/23/20', 'y': 80528},
   {'x': '8/24/20', 'y': 80960}]},
 {'name': 'Romania',
  'data': [{'x': '8/20/20', 'y': 74963},
   {'x': '8/21/20', 'y': 76355},
   {'x': '8/22/20', 'y': 77544},
   {'x': '8/23/20', 'y': 78505},
   {'x': '8/24/20', 'y': 79330}]},
 {'name': 'Belarus',
  'data': [{'x': '8/20/20', 'y': 69950},
   {'x': '8/21/20', 'y': 70111},
   {'x': '8/22/20', 'y': 70285},
   {'x': '8/23/20', 'y': 70468},
   {'x': '8/24/20', 'y': 70645}]},
 {'name': 'Guatemala',
  'data': [{'x': '8/20/20', 'y': 65983},
   {'x': '8/21/20', 'y': 66941},
   {'x': '8/22/20', 'y': 67856},
   {'x': '8/23/20', 'y': 68188},
   {'x': '8/24/20', 'y': 68533}]},
 {'name': 'China',
  'data': [{'x': '8/20/20', 'y': 89567},
   {'x': '8/21/20', 'y': 89616},
   {'x': '8/22/20', 'y': 89654},
   {'x': '8/23/20', 'y': 89695},
   {'x': '8/24/20', 'y': 89718}]},
 {'name': 'United Arab Emirates',
  'data': [{'x': '8/20/20', 'y': 65802},
   {'x': '8/21/20', 'y': 66193},
   {'x': '8/22/20', 'y': 66617},
   {'x': '8/23/20', 'y': 67007},
   {'x': '8/24/20', 'y': 67282}]},
 {'name': 'Netherlands',
  'data': [{'x': '8/20/20', 'y': 66843},
   {'x': '8/21/20', 'y': 67456},
   {'x': '8/22/20', 'y': 68051},
   {'x': '8/23/20', 'y': 68570},
   {'x': '8/24/20', 'y': 69224}]},
 {'name': 'Japan',
  'data': [{'x': '8/20/20', 'y': 59900},
   {'x': '8/21/20', 'y': 60949},
   {'x': '8/22/20', 'y': 61916},
   {'x': '8/23/20', 'y': 62658},
   {'x': '8/24/20', 'y': 63158}]},
 {'name': 'Poland',
  'data': [{'x': '8/20/20', 'y': 59378},
   {'x': '8/21/20', 'y': 60281},
   {'x': '8/22/20', 'y': 61181},
   {'x': '8/23/20', 'y': 61762},
   {'x': '8/24/20', 'y': 62310}]},
 {'name': 'Canada',
  'data': [{'x': '8/20/20', 'y': 125625},
   {'x': '8/21/20', 'y': 126319},
   {'x': '8/22/20', 'y': 126560},
   {'x': '8/23/20', 'y': 126817},
   {'x': '8/24/20', 'y': 127594}]},
 {'name': 'Singapore',
  'data': [{'x': '8/20/20', 'y': 56099},
   {'x': '8/21/20', 'y': 56216},
   {'x': '8/22/20', 'y': 56266},
   {'x': '8/23/20', 'y': 56353},
   {'x': '8/24/20', 'y': 56404}]},
 {'name': 'Portugal',
  'data': [{'x': '8/20/20', 'y': 54992},
   {'x': '8/21/20', 'y': 55211},
   {'x': '8/22/20', 'y': 55452},
   {'x': '8/23/20', 'y': 55597},
   {'x': '8/24/20', 'y': 55720}]},
 {'name': 'Honduras',
  'data': [{'x': '8/20/20', 'y': 52819},
   {'x': '8/21/20', 'y': 53381},
   {'x': '8/22/20', 'y': 53983},
   {'x': '8/23/20', 'y': 54511},
   {'x': '8/24/20', 'y': 55479}]},
 {'name': 'Morocco',
  'data': [{'x': '8/20/20', 'y': 47638},
   {'x': '8/21/20', 'y': 49247},
   {'x': '8/22/20', 'y': 50812},
   {'x': '8/23/20', 'y': 52349},
   {'x': '8/24/20', 'y': 53252}]},
 {'name': 'Nigeria',
  'data': [{'x': '8/20/20', 'y': 50964},
   {'x': '8/21/20', 'y': 51304},
   {'x': '8/22/20', 'y': 51905},
   {'x': '8/23/20', 'y': 52227},
   {'x': '8/24/20', 'y': 52548}]},
 {'name': 'Bahrain',
  'data': [{'x': '8/20/20', 'y': 48303},
   {'x': '8/21/20', 'y': 48661},
   {'x': '8/22/20', 'y': 49038},
   {'x': '8/23/20', 'y': 49330},
   {'x': '8/24/20', 'y': 49719}]},
 {'name': 'Ghana',
  'data': [{'x': '8/20/20', 'y': 43260},
   {'x': '8/21/20', 'y': 43325},
   {'x': '8/22/20', 'y': 43325},
   {'x': '8/23/20', 'y': 43505},
   {'x': '8/24/20', 'y': 43622}]},
 {'name': 'Canada',
  'data': [{'x': '8/20/20', 'y': 125625},
   {'x': '8/21/20', 'y': 126319},
   {'x': '8/22/20', 'y': 126560},
   {'x': '8/23/20', 'y': 126817},
   {'x': '8/24/20', 'y': 127594}]},
 {'name': 'Kyrgyzstan',
  'data': [{'x': '8/20/20', 'y': 42507},
   {'x': '8/21/20', 'y': 42703},
   {'x': '8/22/20', 'y': 42889},
   {'x': '8/23/20', 'y': 43023},
   {'x': '8/24/20', 'y': 43126}]},
 {'name': 'Armenia',
  'data': [{'x': '8/20/20', 'y': 42319},
   {'x': '8/21/20', 'y': 42477},
   {'x': '8/22/20', 'y': 42616},
   {'x': '8/23/20', 'y': 42792},
   {'x': '8/24/20', 'y': 42825}]},
 {'name': 'Ethiopia',
  'data': [{'x': '8/20/20', 'y': 35836},
   {'x': '8/21/20', 'y': 37665},
   {'x': '8/22/20', 'y': 39033},
   {'x': '8/23/20', 'y': 40671},
   {'x': '8/24/20', 'y': 42143}]},
 {'name': 'Algeria',
  'data': [{'x': '8/20/20', 'y': 40258},
   {'x': '8/21/20', 'y': 40667},
   {'x': '8/22/20', 'y': 41068},
   {'x': '8/23/20', 'y': 41460},
   {'x': '8/24/20', 'y': 41858}]},
 {'name': 'Venezuela',
  'data': [{'x': '8/20/20', 'y': 37567},
   {'x': '8/21/20', 'y': 38219},
   {'x': '8/22/20', 'y': 38957},
   {'x': '8/23/20', 'y': 39564},
   {'x': '8/24/20', 'y': 40338}]},
 {'name': 'Switzerland',
  'data': [{'x': '8/20/20', 'y': 39026},
   {'x': '8/21/20', 'y': 39332},
   {'x': '8/22/20', 'y': 39627},
   {'x': '8/23/20', 'y': 39903},
   {'x': '8/24/20', 'y': 40060}]},
 {'name': 'Uzbekistan',
  'data': [{'x': '8/20/20', 'y': 37547},
   {'x': '8/21/20', 'y': 38074},
   {'x': '8/22/20', 'y': 38532},
   {'x': '8/23/20', 'y': 38946},
   {'x': '8/24/20', 'y': 39348}]},
 {'name': 'Afghanistan',
  'data': [{'x': '8/20/20', 'y': 37856},
   {'x': '8/21/20', 'y': 37894},
   {'x': '8/22/20', 'y': 37953},
   {'x': '8/23/20', 'y': 37999},
   {'x': '8/24/20', 'y': 38054}]},
 {'name': 'Azerbaijan',
  'data': [{'x': '8/20/20', 'y': 34759},
   {'x': '8/21/20', 'y': 34921},
   {'x': '8/22/20', 'y': 35105},
   {'x': '8/23/20', 'y': 35274},
   {'x': '8/24/20', 'y': 35426}]},
 {'name': 'Costa Rica',
  'data': [{'x': '8/20/20', 'y': 31075},
   {'x': '8/21/20', 'y': 32134},
   {'x': '8/22/20', 'y': 33084},
   {'x': '8/23/20', 'y': 33820},
   {'x': '8/24/20', 'y': 34463}]},
 {'name': 'Moldova',
  'data': [{'x': '8/20/20', 'y': 31937},
   {'x': '8/21/20', 'y': 32484},
   {'x': '8/22/20', 'y': 33072},
   {'x': '8/23/20', 'y': 33478},
   {'x': '8/24/20', 'y': 33828}]},
 {'name': 'Nepal',
  'data': [{'x': '8/20/20', 'y': 29645},
   {'x': '8/21/20', 'y': 30483},
   {'x': '8/22/20', 'y': 31117},
   {'x': '8/23/20', 'y': 31935},
   {'x': '8/24/20', 'y': 32678}]},
 {'name': 'Kenya',
  'data': [{'x': '8/20/20', 'y': 31441},
   {'x': '8/21/20', 'y': 31763},
   {'x': '8/22/20', 'y': 32118},
   {'x': '8/23/20', 'y': 32364},
   {'x': '8/24/20', 'y': 32557}]},
 {'name': 'Serbia',
  'data': [{'x': '8/20/20', 'y': 30209},
   {'x': '8/21/20', 'y': 30378},
   {'x': '8/22/20', 'y': 30548},
   {'x': '8/23/20', 'y': 30657},
   {'x': '8/24/20', 'y': 30714}]},
 {'name': 'Ireland',
  'data': [{'x': '8/20/20', 'y': 27676},
   {'x': '8/21/20', 'y': 27755},
   {'x': '8/22/20', 'y': 27908},
   {'x': '8/23/20', 'y': 27969},
   {'x': '8/24/20', 'y': 28116}]},
 {'name': 'Austria',
  'data': [{'x': '8/20/20', 'y': 24431},
   {'x': '8/21/20', 'y': 24762},
   {'x': '8/22/20', 'y': 25062},
   {'x': '8/23/20', 'y': 25253},
   {'x': '8/24/20', 'y': 25495}]},
 {'name': 'El Salvador',
  'data': [{'x': '8/20/20', 'y': 23964},
   {'x': '8/21/20', 'y': 24200},
   {'x': '8/22/20', 'y': 24420},
   {'x': '8/23/20', 'y': 24622},
   {'x': '8/24/20', 'y': 24811}]},
 {'name': 'Czechia',
  'data': [{'x': '8/20/20', 'y': 21045},
   {'x': '8/21/20', 'y': 21551},
   {'x': '8/22/20', 'y': 21790},
   {'x': '8/23/20', 'y': 21923},
   {'x': '8/24/20', 'y': 22181}]},
 {'name': 'West Bank and Gaza',
  'data': [{'x': '8/20/20', 'y': 17989},
   {'x': '8/21/20', 'y': 18313},
   {'x': '8/22/20', 'y': 18476},
   {'x': '8/23/20', 'y': 18802},
   {'x': '8/24/20', 'y': 19213}]},
 {'name': 'Cameroon',
  'data': [{'x': '8/20/20', 'y': 18762},
   {'x': '8/21/20', 'y': 18762},
   {'x': '8/22/20', 'y': 18762},
   {'x': '8/23/20', 'y': 18762},
   {'x': '8/24/20', 'y': 18762}]},
 {'name': 'Australia',
  'data': [{'x': '8/20/20', 'y': 24407},
   {'x': '8/21/20', 'y': 24602},
   {'x': '8/22/20', 'y': 24811},
   {'x': '8/23/20', 'y': 24915},
   {'x': '8/24/20', 'y': 25053}]},
 {'name': 'Bosnia and Herzegovina',
  'data': [{'x': '8/20/20', 'y': 17029},
   {'x': '8/21/20', 'y': 17396},
   {'x': '8/22/20', 'y': 17715},
   {'x': '8/23/20', 'y': 17715},
   {'x': '8/24/20', 'y': 18029}]},
 {'name': 'Korea, South',
  'data': [{'x': '8/20/20', 'y': 16670},
   {'x': '8/21/20', 'y': 17002},
   {'x': '8/22/20', 'y': 17399},
   {'x': '8/23/20', 'y': 17665},
   {'x': '8/24/20', 'y': 17945}]},
 {'name': "Cote d'Ivoire",
  'data': [{'x': '8/20/20', 'y': 17249},
   {'x': '8/21/20', 'y': 17310},
   {'x': '8/22/20', 'y': 17374},
   {'x': '8/23/20', 'y': 17471},
   {'x': '8/24/20', 'y': 17506}]},
 {'name': 'Denmark',
  'data': [{'x': '8/20/20', 'y': 16453},
   {'x': '8/21/20', 'y': 16525},
   {'x': '8/22/20', 'y': 16637},
   {'x': '8/23/20', 'y': 16715},
   {'x': '8/24/20', 'y': 16821}]},
 {'name': 'Bulgaria',
  'data': [{'x': '8/20/20', 'y': 14962},
   {'x': '8/21/20', 'y': 15131},
   {'x': '8/22/20', 'y': 15131},
   {'x': '8/23/20', 'y': 15287},
   {'x': '8/24/20', 'y': 15386}]},
 {'name': 'Madagascar',
  'data': [{'x': '8/20/20', 'y': 14154},
   {'x': '8/21/20', 'y': 14218},
   {'x': '8/22/20', 'y': 14277},
   {'x': '8/23/20', 'y': 14327},
   {'x': '8/24/20', 'y': 14402}]},
 {'name': 'North Macedonia',
  'data': [{'x': '8/20/20', 'y': 13194},
   {'x': '8/21/20', 'y': 13308},
   {'x': '8/22/20', 'y': 13458},
   {'x': '8/23/20', 'y': 13595},
   {'x': '8/24/20', 'y': 13673}]},
 {'name': 'Paraguay',
  'data': [{'x': '8/20/20', 'y': 11817},
   {'x': '8/21/20', 'y': 12536},
   {'x': '8/22/20', 'y': 12974},
   {'x': '8/23/20', 'y': 13233},
   {'x': '8/24/20', 'y': 13602}]},
 {'name': 'Lebanon',
  'data': [{'x': '8/20/20', 'y': 10952},
   {'x': '8/21/20', 'y': 11580},
   {'x': '8/22/20', 'y': 12191},
   {'x': '8/23/20', 'y': 12698},
   {'x': '8/24/20', 'y': 13155}]},
 {'name': 'Senegal',
  'data': [{'x': '8/20/20', 'y': 12559},
   {'x': '8/21/20', 'y': 12689},
   {'x': '8/22/20', 'y': 12850},
   {'x': '8/23/20', 'y': 12949},
   {'x': '8/24/20', 'y': 13013}]},
 {'name': 'Canada',
  'data': [{'x': '8/20/20', 'y': 125625},
   {'x': '8/21/20', 'y': 126319},
   {'x': '8/22/20', 'y': 126560},
   {'x': '8/23/20', 'y': 126817},
   {'x': '8/24/20', 'y': 127594}]},
 {'name': 'Sudan',
  'data': [{'x': '8/20/20', 'y': 12582},
   {'x': '8/21/20', 'y': 12623},
   {'x': '8/22/20', 'y': 12682},
   {'x': '8/23/20', 'y': 12836},
   {'x': '8/24/20', 'y': 12903}]},
 {'name': 'Kosovo',
  'data': [{'x': '8/20/20', 'y': 11545},
   {'x': '8/21/20', 'y': 12168},
   {'x': '8/22/20', 'y': 12168},
   {'x': '8/23/20', 'y': 12448},
   {'x': '8/24/20', 'y': 12448}]},
 {'name': 'Zambia',
  'data': [{'x': '8/20/20', 'y': 10372},
   {'x': '8/21/20', 'y': 10627},
   {'x': '8/22/20', 'y': 10831},
   {'x': '8/23/20', 'y': 11082},
   {'x': '8/24/20', 'y': 11148}]},
 {'name': 'Libya',
  'data': [{'x': '8/20/20', 'y': 9707},
   {'x': '8/21/20', 'y': 10121},
   {'x': '8/22/20', 'y': 10437},
   {'x': '8/23/20', 'y': 10437},
   {'x': '8/24/20', 'y': 11009}]},
 {'name': 'Norway',
  'data': [{'x': '8/20/20', 'y': 10197},
   {'x': '8/21/20', 'y': 10275},
   {'x': '8/22/20', 'y': 10299},
   {'x': '8/23/20', 'y': 10323},
   {'x': '8/24/20', 'y': 10395}]},
 {'name': 'Congo (Kinshasa)',
  'data': [{'x': '8/20/20', 'y': 9757},
   {'x': '8/21/20', 'y': 9802},
   {'x': '8/22/20', 'y': 9811},
   {'x': '8/23/20', 'y': 9830},
   {'x': '8/24/20', 'y': 9842}]},
 {'name': 'Malaysia',
  'data': [{'x': '8/20/20', 'y': 9240},
   {'x': '8/21/20', 'y': 9249},
   {'x': '8/22/20', 'y': 9257},
   {'x': '8/23/20', 'y': 9267},
   {'x': '8/24/20', 'y': 9274}]},
 {'name': 'Guinea',
  'data': [{'x': '8/20/20', 'y': 8876},
   {'x': '8/21/20', 'y': 8932},
   {'x': '8/22/20', 'y': 8932},
   {'x': '8/23/20', 'y': 8967},
   {'x': '8/24/20', 'y': 9076}]},
 {'name': 'France',
  'data': [{'x': '8/20/20', 'y': 256534},
   {'x': '8/21/20', 'y': 271960},
   {'x': '8/22/20', 'y': 275562},
   {'x': '8/23/20', 'y': 280459},
   {'x': '8/24/20', 'y': 282414}]},
 {'name': 'Greece',
  'data': [{'x': '8/20/20', 'y': 7934},
   {'x': '8/21/20', 'y': 8138},
   {'x': '8/22/20', 'y': 8381},
   {'x': '8/23/20', 'y': 8664},
   {'x': '8/24/20', 'y': 8819}]},
 {'name': 'Albania',
  'data': [{'x': '8/20/20', 'y': 7967},
   {'x': '8/21/20', 'y': 8119},
   {'x': '8/22/20', 'y': 8275},
   {'x': '8/23/20', 'y': 8427},
   {'x': '8/24/20', 'y': 8605}]},
 {'name': 'Gabon',
  'data': [{'x': '8/20/20', 'y': 8319},
   {'x': '8/21/20', 'y': 8388},
   {'x': '8/22/20', 'y': 8388},
   {'x': '8/23/20', 'y': 8388},
   {'x': '8/24/20', 'y': 8409}]},
 {'name': 'Tajikistan',
  'data': [{'x': '8/20/20', 'y': 8203},
   {'x': '8/21/20', 'y': 8241},
   {'x': '8/22/20', 'y': 8277},
   {'x': '8/23/20', 'y': 8311},
   {'x': '8/24/20', 'y': 8346}]},
 {'name': 'Croatia',
  'data': [{'x': '8/20/20', 'y': 7329},
   {'x': '8/21/20', 'y': 7594},
   {'x': '8/22/20', 'y': 7900},
   {'x': '8/23/20', 'y': 8175},
   {'x': '8/24/20', 'y': 8311}]},
 {'name': 'Haiti',
  'data': [{'x': '8/20/20', 'y': 7997},
   {'x': '8/21/20', 'y': 8016},
   {'x': '8/22/20', 'y': 8050},
   {'x': '8/23/20', 'y': 8082},
   {'x': '8/24/20', 'y': 8110}]},
 {'name': 'Finland',
  'data': [{'x': '8/20/20', 'y': 7842},
   {'x': '8/21/20', 'y': 7871},
   {'x': '8/22/20', 'y': 7906},
   {'x': '8/23/20', 'y': 7920},

## Country-wise

In [28]:
countryDataSpe=pd.DataFrame(confirmedGlobal[confirmedGlobal['Country/Region']=='China'][confirmedGlobal.columns[4:-1]].sum()).reset_index()
countryDataSpe.columns=['country','values']
countryDataSpe['lagVal']=countryDataSpe['values'].shift(1).fillna(0)
countryDataSpe['incrementVal']=countryDataSpe['values']-countryDataSpe['lagVal']
countryDataSpe['rollingMean']=countryDataSpe['incrementVal'].rolling(window=4).mean()
countryDataSpe=countryDataSpe.fillna(0)
datasetsForLine=[{'label':'Daily Cumulated Data','data':countryDataSpe['values'].values.tolist()},
                {'label':'Rolling Mean 4 days','data':countryDataSpe['rollingMean'].values.tolist()}]

In [32]:
countryDataSpe=pd.DataFrame(confirmedGlobal[confirmedGlobal['Country/Region']=='China'][confirmedGlobal.columns[4:-1]].sum()).reset_index()
countryDataSpe.columns=['country','values']

In [33]:
confirmedGlobal

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,8/16/20,8/17/20,8/18/20,8/19/20,8/20/20,8/21/20,8/22/20,8/23/20,8/24/20,NewContryCode
0,NaN,Afghanistan,33.939110,67.709953,0,0,0,0,0,0,...,37596,37599,37599,37599,37856,37894,37953,37999,38054,Afghanistan
1,NaN,Albania,41.153300,20.168300,0,0,0,0,0,0,...,7380,7499,7654,7812,7967,8119,8275,8427,8605,Albania
2,NaN,Algeria,28.033900,1.659600,0,0,0,0,0,0,...,38583,39025,39444,39847,40258,40667,41068,41460,41858,Algeria
3,NaN,Andorra,42.506300,1.521800,0,0,0,0,0,0,...,989,1005,1005,1024,1024,1045,1045,1045,1060,Andorra
4,NaN,Angola,-11.202700,17.873900,0,0,0,0,0,0,...,1906,1935,1966,2015,2044,2068,2134,2171,2222,Angola
5,NaN,Antigua and Barbuda,17.060800,-61.796400,0,0,0,0,0,0,...,93,93,93,94,94,94,94,94,94,Antigua and Barbuda
6,NaN,Argentina,-38.416100,-63.616700,0,0,0,0,0,0,...,294569,299126,305966,312659,320884,329043,336802,342154,350867,Argentina
7,NaN,Armenia,40.069100,45.038200,0,0,0,0,0,0,...,41663,41701,41846,42056,42319,42477,42616,42792,42825,Armenia
8,Australian Capital Territory,Australia,-35.473500,149.012400,0,0,0,0,0,0,...,113,113,113,113,113,113,113,113,113,AustraliaAustralian Capital Territory
9,New South Wales,Australia,-33.868800,151.209300,0,0,0,0,3,4,...,3957,3959,3966,3971,3972,3981,3985,3988,3991,AustraliaNew South Wales
10,Northern Territory,Australia,-12.463400,130.845600,0,0,0,0,0,0,...,33,33,33,33,33,33,33,33,33,AustraliaNorthern Territory
11,Queensland,Australia,-27.469800,153.025100,0,0,0,0,0,0,...,1091,1091,1092,1093,1094,1103,1105,1106,1106,AustraliaQueensland
12,South Australia,Australia,-34.928500,138.600700,0,0,0,0,0,0,...,461,462,462,462,462,462,462,463,463,AustraliaSouth Australia
13,Tasmania,Australia,-42.882100,147.327200,0,0,0,0,0,0,...,230,230,230,230,230,230,230,230,230,AustraliaTasmania
14,Victoria,Australia,-37.813600,144.963100,0,0,0,0,1,1,...,17027,17238,17446,17683,17852,18029,18231,18330,18464,AustraliaVictoria
15,Western Australia,Australia,-31.950500,115.860500,0,0,0,0,0,0,...,646,647,647,651,651,651,652,652,653,AustraliaWestern Australia
16,NaN,Austria,47.516200,14.550100,0,0,0,0,0,0,...,23370,23534,23829,24084,24431,24762,25062,25253,25495,Austria
17,NaN,Azerbaijan,40.143100,47.576900,0,0,0,0,0,0,...,34219,34343,34474,34620,34759,34921,35105,35274,35426,Azerbaijan
18,NaN,Bahamas,25.025885,-78.035889,0,0,0,0,0,0,...,1315,1329,1424,1531,1610,1703,1703,1765,1765,Bahamas
19,NaN,Bahrain,26.027500,50.550000,0,0,0,0,0,0,...,46835,47185,47581,47950,48303,48661,49038,49330,49719,Bahrain
20,NaN,Bangladesh,23.685000,90.356300,0,0,0,0,0,0,...,276549,279144,282344,285091,287959,290360,292625,294598,297083,Bangladesh
21,NaN,Barbados,13.193900,-59.543200,0,0,0,0,0,0,...,151,152,153,155,156,157,158,161,161,Barbados
22,NaN,Belarus,53.709800,27.953400,0,0,0,0,0,0,...,69516,69589,69673,69801,69950,70111,70285,70468,70645,Belarus
23,NaN,Belgium,50.833300,4.469936,0,0,0,0,0,0,...,78323,78534,78897,79479,80178,80894,81468,81936,82092,Belgium
24,NaN,Belize,17.189900,-88.497600,0,0,0,0,0,0,...,452,475,475,553,605,648,668,686,713,Belize
25,NaN,Benin,9.307700,2.315800,0,0,0,0,0,0,...,2063,2063,2063,2095,2095,2095,2115,2115,2115,Benin
26,NaN,Bhutan,27.514200,90.433600,0,0,0,0,0,0,...,138,141,147,147,153,154,155,155,156,Bhutan
27,NaN,Bolivia,-16.290200,-63.588700,0,0,0,0,0,0,...,100344,101223,103019,105050,106065,107435,108427,109149,110148,Bolivia
28,NaN,Bosnia and Herzegovina,43.915900,17.679100,0,0,0,0,0,0,...,15801,16111,16351,16691,17029,17396,17715,17715,18029,Bosnia and Herzegovina
29,NaN,Botswana,-22.328500,24.684900,0,0,0,0,0,0,...,1214,1308,1308,1308,1308,1308,1308,1308,1562,Botswana
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
236,NaN,Thailand,15.870032,100.992541,2,3,5,7,8,8,...,3378,3378,3382,3382,3389,3390,3390,3395,3402,Thailand
237,NaN,Timor-Leste,-8.874217,125.727539,0,0,0,0,0,0,...,25,25,25,25,25,25,26,26,26,Timor-Leste
238,NaN,Togo,8.619500,0.824800,0,0,0,0,0,0,...,1147,1154,1173,1190,1212,1239,1275,1277,1295,Togo
239,NaN,Trinidad and Tobago,10.691800,-61.222500,0,0,0,0,0,0,...,552,588,629,686,767,864,930,1007,1099,Trinidad and Tobago
240,NaN,Tunisia,33.886917,9.537499,0,0,0,0,0,0,...,2107,2185,2314,2427,2543,2607,2738,2818,2893,Tunisia
241,NaN,Turkey,38.963700,35.243300,0,0,0,0,0,0,...,249309,250542,251805,253108,254520,255723,257032,258249,259692,Turkey
242,NaN,US,40.000000,-100.000000,1,1,2,2,5,5,...,5403213,5438325,5482416,5529824,5573847,5622540,5667112,5701679,5739724,US
243,NaN,Uganda,1.373333,32.290275,0,0,0,0,0,0,...,1500,1560,1603,1656,1750,1848,2166,2263,2362,Uganda
244,NaN,Ukraine,48.379400,31.165600,0,0,0,0,0,0,...,93490,95007,96653,98658,100810,102948,105337,107379,109234,Ukraine
245,NaN,United Arab Emirates,23.424076,53.847818,0,0,0,0,0,0,...,64312,64541,64906,65341,65802,66193,66617,67007,67282,United Arab Emirates
246,Anguilla,United Kingdom,18.220600,-63.068600,0,0,0,0,0,0,...,3,3,3,3,3,3,3,3,3,United KingdomAnguilla
247,Bermuda,United Kingdom,32.307800,-64.750500,0,0,0,0,0,0,...,162,166,166,166,166,167,167,167,168,United KingdomBermuda
248,British Virgin Islands,United Kingdom,18.420700,-64.640000,0,0,0,0,0,0,...,9,9,11,11,11,21,21,21,21,United KingdomBritish Virgin Islands
249,Cayman Islands,United Kingdom,19.313300,-81.254600,0,0,0,0,0,0,...,203,203,203,205,205,205,205,205,205,United KingdomCayman Islands
250,Channel Islands,United Kingdom,49.372300,-2.364400,0,0,0,0,0,0,...,607,609,609,613,613,614,614,614,616,United KingdomChannel Islands
251,Falkland Islands (Malvinas),United Kingdom,-51.796300,-59.523600,0,0,0,0,0,0,...,13,13,13,13,13,13,13,13,13,United KingdomFalkland Islands (Malvinas)
252,Gibraltar,United Kingdom,36.140800,-5.353600,0,0,0,0,0,0,...,215,217,222,223,229,231,239,246,248,United KingdomGibraltar
253,Isle of Man,United Kingdom,54.236100,-4.548100,0,0,0,0,0,0,...,336,336,336,336,336,336,336,336,336,United KingdomIsle of Man
254,Montserrat,United Kingdom,16.742498,-62.187366,0,0,0,0,0,0,...,13,13,13,13,13,13,13,13,13,United KingdomMontserrat
255,Turks and Caicos Islands,United Kingdom,21.694000,-71.797900,0,0,0,0,0,0,...,298,298,315,327,334,347,383,383,383,United KingdomTurks and Caicos Islands
256,NaN,United Kingdom,55.378100,-3.436000,0,0,0,0,0,0,...,318484,319197,320286,321098,322280,323313,324601,325642,326614,United Kingdom
257,NaN,Uruguay,-32.522800,-55.765800,0,0,0,0,0,0,...,1440,1457,1485,1493,1506,1516,1521,1527,1533,Uruguay
258,NaN,Uzbekistan,41.377491,64.585262,0,0,0,0,0,0,...,35329,35702,36352,37112,37547,38074,38532,38946,39348,Uzbekistan
259,NaN,Venezuela,6.423800,-66.589700,0,0,0,0,0,0,...,33755,34802,35697,36868,37567,38219,38957,39564,40338,Venezuela
260,NaN,Vietnam,14.058324,108.277199,0,2,2,2,2,2,...,964,983,989,994,1007,1009,1014,1016,1022,Vietnam
261,NaN,West Bank and Gaza,31.952200,35.233200,0,0,0,0,0,0,...,16534,16844,17306,17606,17989,18313,18476,18802,19213,West Bank and Gaza
262,NaN,Western Sahara,24.215500,-12.885800,0,0,0,0,0,0,...,10,10,10,10,10,10,10,10,10,Western Sahara
263,NaN,Yemen,15.552727,48.516388,0,0,0,0,0,0,...,1869,1882,1889,1892,1899,1906,1907,1911,1916,Yemen
264,NaN,Zambia,-13.133897,27.849332,0,0,0,0,0,0,...,9343,9839,9981,10218,10372,10627,10831,11082,11148,Zambia
265,NaN,Zimbabwe,-19.015438,29.154857,0,0,0,0,0,0,...,5261,5308,5378,5643,5745,5815,5893,5930,6070,Zimbabwe